import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/header";
import Footer from "../components/footer";
import { HEADER_FOOTER_ENDPOINT } from "../utils/constants/endpoints";
import axios from "axios";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const dynamic = "force-dynamic";
// export const revalidate = 600;

export default async function RootLayout({ children }) {
  const { header, footer } = await axios.get(HEADER_FOOTER_ENDPOINT);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header header={header} />
        <main>{children}</main>
        <Footer footer={footer} />
      </body>
    </html>
  );
}
